### ISSUE TITLE
FLOOR support

### ISSUE THREAD

**Issue by moacirosa** [orocrm/doctrine-extensions#27]
Hello Guys,

First of all congratulations for this amazing project! I'm using the extension and I need to use the math `FLOOR` operator. I'm not sure that it would be possible to make it work out of the box. I've added a line like this in my `config.yml`:

``` yml
orm:
    auto_generate_proxy_classes: "%kernel.debug%"
      naming_strategy: doctrine.orm.naming_strategy.underscore
      auto_mapping: true
      dql:
          numeric_functions:
          floor:    Oro\ORM\Query\AST\Functions\SimpleFunction
```

Then I've added two small classes named `Floor` in `MySQL` and `Postgres` namespaces. Does it make sense for you? If so... Do you believe that a pull request for supporting `FLOOR` out of the box would be part of the scope of this project?
